---
abstract: 'Structure oriented CSS manipulation.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Structure
no_index:
  directory:
    - inc
    - t
requires:
  Class::Utils: 0.03
  Error::Pure: 0.11
  List::MoreUtils: 0
  Readonly: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CSS-Structure
  homepage: https://github.com/tupinek/CSS-Structure
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/CSS-Structure
version: '0.01'
